export default {
	NEWS_FETCHING: "NEWS_FETCHING",
	NEWS_FETCH_SUCCESS: "NEWS_FETCH_SUCCESS",
	NEWS_FETCH_ERROR: "NEWS_FETCH_ERROR",
	NEWS_LOAD_MORE_SUCCESS: "NEWS_LOAD_MORE_SUCCESS",
	SEARCH_SUCCESS: "SEARCH_SUCCESS",
	OPEN_ARTICLE: "OPEN_ARTICLE",
	HISTORY_FETCHING: "HISTORY_FETCHING",
	HISTORY_FETCH_SUCCESS: "HISTORY_FETCH_SUCCESS",
	HISTORY_FETCH_ERROR: "HISTORY_FETCH_ERROR",
};